version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8088
      # AFEGIM EL PROXY AMB UN PORT NO PRIVILEGIAT
  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80" # Mapegem el 8081 (fora) al 80 (dins del contenidor)
    depends_on:
      - frontend
      - backend
