version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # AQUESTA ÉS LA CLAU: Docker carregarà el .env de l'arrel
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8088